### ISSUE TITLE
Cannot load pretrain metafg_2_inat21_384

### ISSUE THREAD

**Issue by DuyMinhLe13** [dqshuai/MetaFormer#32]
I use default config for MetaFG_2 but the errors in load_state_dict occured. Could you provide config of MetaFG_2_384 ?

**Comment by sun-jiao** [comment]
Config file for metafg_2_inat21_384:

```
DATA:
  IMG_SIZE: 384
  ADD_META: True
MODEL:
  TYPE: MetaFG
  NAME: MetaFG_meta_2
  EXTRA_TOKEN_NUM: 3
  META_DIMS: [ 4, 3 ]
  NUM_CLASSES: 10000
```

I am not a member of their team. I just tried it out.
